Usual notebook magic

In [1]:
import pythran

In [2]:
%load_ext pythran.magic

Define the core of a ufunc

In [3]:
%%pythran
#pythran export ufunc incr(float64)
def incr(v):
    "increment a value by one"
    return v + 1

Ufunc work on scalar:

In [4]:
incr(3)

4.0

In [5]:
"increment a value by one" in incr.__doc__

True

And on numpy arrays:

In [6]:
import numpy as np
incr(np.ones(10))

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

Let's write a naive candidate for broadcasting:

In [7]:
%%pythran
#pythran export ufunc avg(int, int)
def avg(i, j):
    return type(i)((i + j) // 2)

In [8]:
avg(np.ones(4, dtype=int), 9)

array([5, 5, 5, 5])

In [9]:
avg(np.ones((4, 4), dtype=int), 5 * np.ones(4, dtype=int))

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

It's possible to support multiple signatures for the same function:

In [10]:
%%pythran
#pythran export ufunc decr(int32)
#pythran export ufunc decr(uint32)
def decr(x):
    from numpy import int32, uint32
    if isinstance(x, int32):
        return int32(x - 1)
    else:
        return uint32(x if x == 0 else x - 1)

In [11]:
decr(np.int32(0)), decr(np.uint32(0))

(-1, 0)